UPDATE FILE1_11_ALL
SET FILE1_11_ALL.DISCOUNT_INV = VW_FILE6_20.DISCOUNT,
FILE1_11_ALL.TAX_INV = VW_FILE6_20.TAX,
FILE1_11_ALL.TOTAL_ITEM_INV = VW_FILE6_20.TOTAL_ITEM
FROM FILE1_11_ALL 
INNER JOIN VW_FILE6_20 ON FILE1_11_ALL.DOC_ID = VW_FILE6_20.DOC_NO
AND FILE1_11_ALL.[TYPE] = '6'


SELECT F.DISCOUNT_RATE, V.DISCOUNT_rate
FROM FILE1_11_ALL AS F INNER JOIN VW_FILE6_20 AS V
ON F.DOC_ID = V.DOC_NO
AND F.TYPE = '6'
WHERE ROUND(F.DISCOUNT_rATE,6) <> ROUND(V.DISCOUNT_RATE,6)


SELECT F.TAX_RATE, V.TAX_rate
FROM FILE1_11_ALL AS F INNER JOIN VW_FILE6_20 AS V
ON F.DOC_ID = V.DOC_NO
AND F.TYPE = '6'
WHERE ROUND(F.TAX_rATE,6) <> ROUND(V.TAX_RATE,6)
