SELECT V.DATE,V.BRANCH,DOC_NO,F.DISCOUNT_RATE, V.DISCOUNT_rate,V.TOTAL_ITEM,F.TOTAL_ITEM_INV
FROM FILE1_11_ALL AS F INNER JOIN VW_FILE6_20 AS V
ON F.DOC_ID = V.DOC_NO
AND F.TYPE = '6'
WHERE ROUND(F.DISCOUNT_rATE,6) <> ROUND(V.DISCOUNT_RATE,6)


SELECT F.TAX_RATE, V.TAX_rate
FROM FILE1_11_ALL AS F INNER JOIN VW_FILE6_20 AS V
ON F.DOC_ID = V.DOC_NO
AND F.TYPE = '6'
WHERE ROUND(F.TAX_rATE,6) <> ROUND(V.TAX_RATE,6)
