VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "ClsError"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Number As Long
Public Source As String
Public Description As String

' ???? ?????? ?????? ?????? ????? ?????
Public Sub Raise(ByVal ErrNumber As Long, ByVal ErrSource As String, ByVal ErrDescription As String)
    Number = ErrNumber
    Source = ErrSource
    Description = ErrDescription
End Sub
